// --- Dados Simulados Globais ---
const CIDADE_CENTRO = [-25.43, -49.27]; // Ex: Curitiba
const CIDADE_ZOOM = 11;

const campaignDetailsData = {
    "global_camp_gripe": { title: "Campanha Nacional de Vacinação Contra Gripe (IA)", description: "Incentivar a vacinação da população contra o vírus Influenza, com foco em grupos de risco.", audience: "Idosos (60+), crianças (6m-5a), gestantes, profissionais de saúde.", actions: ["Divulgação em mídia local e redes sociais", "Disponibilização de vacinas em todos os postos e unidades móveis em áreas de baixa cobertura", "Busca ativa de não vacinados em grupos prioritários", "Parceria com escolas e empresas"], priority: "Alta", region: "Todo o município" },
    "regional_camp_zika_norte": { title: "Prevenção Intensificada ao Zika Vírus - Região Norte (IA)", description: "Alertar sobre riscos e métodos de prevenção do Zika, devido ao aumento de vetores.", audience: "Moradores da Região Norte, especialmente gestantes e mulheres em idade fértil.", actions: ["Visitas domiciliares de agentes de endemias", "Distribuição de material informativo e repelentes", "Mutirões de limpeza e eliminação de criadouros", "Palestras em centros comunitários"], priority: "Alta", region: "Região Norte" },
    "dengue_leste": { title: "Combate Urgente à Dengue - Região Leste (IA)", description: "Resposta rápida ao aumento significativo de casos de Dengue, visando contenção imediata.", audience: "Todos os moradores da Região Leste.", actions: ["Nebulização espacial (fumacê) em áreas críticas", "Remoção de criadouros em imóveis públicos e privados", "Orientação casa a casa sobre prevenção e sintomas", "Instalação de postos de hidratação rápida"], priority: "Crítica", region: "Região Leste" },
};

const alertDetailsData = {
    "alert_dengue_leste_01": { title: "Surto de Dengue na Região Leste", severity: "critical", description: "Aumento de 35% nos casos suspeitos de dengue nos últimos 3 dias, ultrapassando limite epidêmico.", area: "Região Leste (Distritos X, Y, Z)", dataObserved: "89 casos suspeitos reportados, vs 65 na média anterior. Índice de Infestação Predial: 5.2%.", actions: ["Ativar protocolo de surto nível 3 (municipal)", "Mobilizar agentes de endemias para bloqueio de foco e eliminação de criadouros em toda a região", "Intensificar comunicação de risco com a população", "Verificar capacidade de atendimento nas UBSs da região"], timestamp: "2025-05-21 08:30:00" },
    "alert_sobrecarga_cardio_centro": { title: "Sobrecarga Crítica: Cardiologia na Região Central", severity: "critical", description: "Tempo de espera para consulta cardiológica na Região Central atingiu 25 dias. Todos os cardiologistas da região com agenda lotada por 30+ dias.", area: "Região Central (Hospital Municipal e UBS Central)", dataObserved: "Fila de espera: 150 pacientes. Capacidade de atendimento: 100/mês. Último remanejamento há 45 dias.", actions: ["Analisar possibilidade de remanejamento emergencial de cardiologistas de outras regiões menos demandadas", "Avaliar contratação temporária ou horas extras", "Comunicar unidades para triagem rigorosa de encaminhamentos", "Priorizar casos urgentes"], timestamp: "2025-05-20 17:00:00" },
    "alert_vacina_norte_02": { title: "Baixa Adesão à Vacina X na Região Norte", severity: "warning", description: "Cobertura vacinal para a vacina X (Sarampo) abaixo de 50% da meta na Região Norte, risco de surto.", area: "Região Norte (Bairros A, B)", dataObserved: "Apenas 40% da população alvo (crianças 1-5 anos) vacinada. Meta: 95%.", actions: ["Intensificar divulgação sobre a importância da vacina X", "Verificar disponibilidade de doses e horários de vacinação nos postos da Região Norte", "Considerar busca ativa para grupos prioritários e vacinação em creches/escolas", "Campanha informativa sobre riscos do sarampo"], timestamp: "2025-05-20 14:00:00" },
    "alert_estoque_rural_03": { title: "Estoque Baixo: Medicamento Y - Zona Rural", severity: "info", description: "Sistema de IA prevê possível necessidade de reposição do medicamento Y (Hipertensão) no Posto Rural Alfa em 5 dias.", area: "Posto Rural Alfa (Zona Rural)", dataObserved: "Estoque atual: 15 unidades. Consumo médio: 2/dia. Próxima entrega programada: 10 dias.", actions: ["Confirmar estoque físico no posto via contato telefônico", "Providenciar reposição antecipada se necessário", "Verificar consumo em outras unidades rurais"], timestamp: "2025-05-21 10:15:00" },
};

// ... (todo o JS extraído de <script> em index5.html) ...
